import { expect, test } from '@playwright/test'

const dismissGlobalModals = async page => {
  for (let attempt = 0; attempt < 10; attempt += 1) {
    const close = page.locator('.ui-modal-overlay.is-teleported .ui-modal-close:visible').first()
    if (!await close.count()) return
    await close.click()
    await page.waitForTimeout(100)
  }
}

test('camp upgrade deep links show source-level rewards, materials, and terminal state', async ({ page }, testInfo) => {
  await page.goto('/#/facilities?facility=camp&mode=building&building=center&level=1')
  await dismissGlobalModals(page)
  const camp = page.locator('.camp-panel')
  await expect(camp.getByRole('heading', { name: '营地中心', exact: true })).toBeVisible()
  await expect(camp.getByRole('heading', { name: '1级 → 2级' })).toBeVisible()
  await expect(camp.getByRole('heading', { name: '升级奖励', exact: true })).toBeVisible()
  await expect(camp.locator('.camp-building-choice')).toHaveCount(7)
  await page.screenshot({ path: testInfo.outputPath('camp-building-top.png') })
  const firstReward = camp.locator('.camp-materials').filter({ has: page.getByRole('heading', { name: '升级奖励', exact: true }) }).locator('.ui-reward-card').first()
  await firstReward.click()
  await expect(page).toHaveURL(/itemId=item_50004/)
  const modal = page.locator('.app-main > .ui-modal-host .ui-modal-overlay')
  await expect(modal).toBeVisible()
  await modal.locator('.ui-modal-close').click()
  await expect(page).not.toHaveURL(/itemId=/)
  await expect(camp.getByRole('heading', { name: '1级 → 2级' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('camp-building.png'), fullPage: true })

  await camp.getByRole('button', { name: '7级', exact: true }).click()
  await expect(camp.getByRole('heading', { name: '7级 · 满级' })).toBeVisible()
  await expect(camp.getByRole('heading', { name: '升级消耗', exact: true })).toHaveCount(0)
  await camp.getByRole('button', { name: '料理台', exact: true }).click()
  await camp.getByRole('button', { name: '3级', exact: true }).click()
  await expect(camp.locator('.ui-info-row').filter({ hasText: '生命值' }).first()).toContainText('+1000')
})

test('research categories, target-level conditions, prerequisite and browser history stay in sync', async ({ page }, testInfo) => {
  await page.goto('/#/facilities?facility=camp&mode=research&research=collect_stone&level=2')
  await dismissGlobalModals(page)
  const camp = page.locator('.camp-panel')
  await expect(camp.getByRole('heading', { name: '采石技巧', exact: true })).toBeVisible()
  await expect(camp.getByText('石头采集速度提升 10% → 20%', { exact: true })).toBeVisible()
  await expect(camp.getByText('15 分钟', { exact: true })).toBeVisible()
  await camp.getByRole('button', { name: '砍伐技巧 1级', exact: true }).click()
  await expect(page).toHaveURL(/research=collect_tree/)
  await expect(camp.getByRole('heading', { name: '砍伐技巧', exact: true })).toBeVisible()
  await camp.getByRole('button', { name: '营地中心 1级', exact: true }).click()
  await expect(camp.getByRole('heading', { name: '营地中心', exact: true })).toBeVisible()
  await page.goBack()
  await expect(camp.getByRole('heading', { name: '砍伐技巧', exact: true })).toBeVisible()

  await camp.getByRole('button', { name: '冒险研究', exact: true }).click()
  await camp.getByRole('button', { name: '武器养护', exact: true }).click()
  await camp.getByRole('button', { name: '10级', exact: true }).click()
  await expect(camp.getByText('全局物理攻击提升 9% → 10%', { exact: true })).toBeVisible()
  await expect(camp.getByText('12 小时', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('camp-research.png'), fullPage: true })
  await page.evaluate(() => document.documentElement.classList.add('dark-mode'))
  const activeColor = await camp.locator('.ui-filter-pill.is-active').first().evaluate(element => getComputedStyle(element).color)
  expect(activeColor).toBe('rgb(223, 206, 179)')
  await page.screenshot({ path: testInfo.outputPath('camp-research-dark.png'), fullPage: true })
  const layout = await camp.evaluate(element => ({ width: element.clientWidth, scroll: element.scrollWidth }))
  expect(layout.scroll).toBeLessThanOrEqual(layout.width + 1)
  const brokenIcons = await camp.locator('.camp-heading img').evaluateAll(images => images.filter(image => !image.complete || image.naturalWidth === 0).length)
  expect(brokenIcons).toBe(0)
  await camp.getByRole('button', { name: '返回研究树', exact: true }).click()
  await camp.getByRole('button', { name: '破甲战术', exact: true }).click()
  await camp.getByRole('button', { name: '10级', exact: true }).click()
  await expect(camp.getByText('· 营地中心 8级', { exact: true })).toBeVisible()
  await expect(camp.getByRole('button', { name: '营地中心 8级', exact: true })).toHaveCount(0)
})

test('research overview uses original game cards and linked branches on desktop and mobile', async ({ page }, testInfo) => {
  await page.goto('/#/facilities?facility=camp&mode=research&group=collect')
  await dismissGlobalModals(page)
  const camp = page.locator('.camp-panel')
  await expect(camp.locator('.research-node')).toHaveCount(9)
  await expect(camp.locator('.research-tree-lines path')).toHaveCount(8)
  await expect(camp.getByRole('combobox')).toHaveCount(0)
  await expect.poll(() => camp.locator('.research-node img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0))).toBe(true)
  expect(await camp.locator('.research-node').first().evaluate(element => getComputedStyle(element).backgroundImage)).toContain('build_tree_botm.webp')
  expect(await camp.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  const root = camp.locator('[data-research="collect_tree"]')
  const diagram = camp.locator('.research-tree-scroll')
  const rootBox = await root.boundingBox()
  const diagramBox = await diagram.boundingBox()
  expect(rootBox.x).toBeGreaterThanOrEqual(diagramBox.x)
  expect(rootBox.x + rootBox.width).toBeLessThanOrEqual(diagramBox.x + diagramBox.width)
  // Dragging from a card pans the map without opening that research.
  await root.scrollIntoViewIfNeeded()
  const dragBox = await root.boundingBox()
  await page.mouse.move(dragBox.x + dragBox.width / 2, dragBox.y + dragBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(dragBox.x + dragBox.width / 2 - 100, dragBox.y + dragBox.height / 2, { steps: 10 })
  await page.mouse.up()
  expect(await diagram.evaluate(element => element.scrollLeft)).toBeGreaterThan(80)
  await expect(camp.locator('.research-node')).toHaveCount(9)
  expect(await diagram.evaluate(element => getComputedStyle(element).scrollbarWidth)).toBe('none')
  await diagram.evaluate(element => { element.scrollLeft = 0 })
  await page.screenshot({ path: testInfo.outputPath('research-tree.png') })
  await camp.getByRole('button', { name: '采石技巧', exact: true }).click()
  await expect(camp.getByRole('heading', { name: '采石技巧', exact: true })).toBeVisible()
  await camp.getByRole('button', { name: '返回研究树', exact: true }).click()
  await camp.getByPlaceholder('搜索研究、效果或材料...').fill('铜矿鉴定')
  await expect(camp.locator('.camp-count .count-num')).toHaveText('1')
  await expect(camp.locator('.research-node:not(.is-context)')).toHaveCount(1)
  await expect(camp.locator('.research-node.is-context')).toHaveCount(3)
  await camp.getByRole('button', { name: '铜矿鉴定', exact: true }).click()
  await expect(camp.getByRole('heading', { name: '铜矿鉴定', exact: true })).toBeVisible()
})

test('malformed facility data shows an error without a blank camp page', async ({ page }) => {
  await page.route('**/data/parsed/facilities.json*', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify([{ key: 'camp', name: '营地' }]) }))
  await page.goto('/#/facilities?facility=camp&mode=research')
  await dismissGlobalModals(page)
  await expect(page.getByText(/加载失败：.*数据格式不完整/)).toBeVisible()
  await expect(page.getByText('正在整理设施数据...', { exact: true })).toHaveCount(0)
  const filter = page.locator('.facilities-page > .filter-panel')
  await expect(filter.getByRole('tab')).toHaveCount(3)
  await expect(filter.getByPlaceholder('搜索研究、效果或材料...')).toBeVisible()
})

test('research improved formulas use existing facility recipes and search has an empty state', async ({ page }) => {
  await page.goto('/#/facilities?facility=camp&mode=research&research=blacksmithCarbonFormula&level=1')
  await dismissGlobalModals(page)
  const camp = page.locator('.camp-panel')
  await expect(camp.getByRole('heading', { name: '高效制碳', exact: true })).toBeVisible()
  await camp.locator('.camp-links').getByRole('button', { name: '木炭', exact: true }).click()
  await expect(page).toHaveURL(/facility=blacksmith&mode=crafting&level=1&item=item_10083/)
  await expect(page.locator('.facility-recipe.is-target').first()).toBeVisible()
  await page.goBack()
  await expect(camp.getByRole('heading', { name: '高效制碳', exact: true })).toBeVisible()
  await camp.getByPlaceholder('搜索研究、效果或材料...').fill('不存在的研究项目xyz')
  await expect(camp.getByText('没有匹配的营地项目', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '设施配方', exact: true }).click()
  await expect(page.getByRole('button', { name: '锻造台', exact: true })).toBeVisible()
})
