import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.route('**/data/notice.json*', route => route.fulfill({ json: { notices: [] } }))
})

test('combat rules lead with limits and retain readable search results after reload', async ({ page }, testInfo) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/rewards?tab=combat_rules')
  const rules = page.locator('.combat-rules')
  await expect(rules.locator('.ui-section').first()).toContainText('属性上限')
  await expect(rules.locator('h4').first()).toHaveText('冷却缩减 最多 50%')
  await expect(rules).toContainText('基础攻速的 4 倍')
  await expect(page.getByRole('button', { name: '占位奖励3', exact: true })).toHaveCount(0)
  await expect(rules).not.toContainText('CalculateMaster')
  const search = page.getByPlaceholder('搜索战斗规则，如冷却、暴击、护盾...')
  await search.fill('胜利恢复')
  await expect(rules).toContainText('一次生命恢复 = 取整')
  await expect(rules.locator('[data-rule-section="limits"]')).toHaveCount(0)
  await expect.poll(() => new URLSearchParams(page.url().split('?')[1]).get('q')).toBe('胜利恢复')
  await page.reload()
  await expect(search).toHaveValue('胜利恢复')
  await expect(rules).toContainText('不是战斗中每秒自动回血或回蓝')
  await search.fill('宠物属性')
  const petRules = rules.locator('[data-rule-section="pets"]')
  await expect(petRules.locator('.combat-rules__formula p')).toHaveCount(7)
  await expect(petRules).toContainText('物理攻击 =（宠物基础攻击 + 个体攻击 × 当前等级）× 1.5')
  await expect(petRules).toContainText('最大生命 = 取整［（宠物基础生命 + 个体生命 × 当前等级）× 3］')
  await expect(petRules).toContainText('计算结果是百分数')
  await expect(petRules).not.toContainText('petSetting')
  await expect.poll(() => rules.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('pet-formulas.png') })
  await search.fill('防御换算系数')
  await expect(rules).toContainText('0.6125')
  await expect.poll(() => rules.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await search.fill('没有这条规则xyz')
  await expect(rules).toContainText('未找到匹配的战斗规则')
  await search.fill('')
  await expect(rules.locator('[data-rule-section="limits"]')).toBeVisible()
  await expect.poll(() => rules.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('combat-rules.png') })
  await page.evaluate(() => document.documentElement.classList.add('dark-mode'))
  await expect.poll(() => rules.evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(46, 34, 23)')
  await page.screenshot({ path: testInfo.outputPath('combat-rules-dark.png') })
  expect(errors).toEqual([])
})

test('legacy placeholder link displays rules even when reward data fails', async ({ page }) => {
  await page.route('**/parsed-pvp.json*', route => route.abort())
  await page.goto('/#/rewards?tab=ph3&q=护盾')
  await expect(page.locator('.combat-rules')).toContainText('先扣护盾，再扣生命')
  await expect(page.getByRole('button', { name: '战斗规则', exact: true })).toBeVisible()
  await expect(page.getByPlaceholder('搜索战斗规则，如冷却、暴击、护盾...')).toHaveValue('护盾')
})
